name: ppa

on:
  push:
    branches:
      - main
      - master

jobs:
    create-ppa:
        name: Create PPA
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true

            - name: Setup Go
              uses: actions/setup-go@v1
              with:
                  go-version: 1.15

            - name: Metadata
              id: metadata
              run: |
                  # todo handle these error cases
                  #git_description=$(git describe --tags --long) || echo "0.0.0-001-$(git rev-parse --short HEAD)"
                  git_description="$0.0.0-001-$(git rev-parse --short HEAD)"
                  version=$(echo "${git_description}" | awk -F- '{print $(1)}' | sed 's/^v//')
                  revision=$(echo "${git_description}" | awk -F- '{print $(NF-1)}')
                  commit=$(echo "${git_description}" | awk -F- '{print $(NF)}'  | sed 's/^g//')
                  echo "::set-output name=version::$version"
                  echo "::set-output name=revision::$revision"
                  echo "::set-output name=commit::$commit"

            - name: Install packaging tools
              run: |
                  sudo apt install gnupg dput dh-make devscripts lintian
            
                  #- name: Import gpg keys
                  #  env: # Or as an environment variable
                  #    GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE }}
                  #    GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC }}
                  #  run: |
                  #      gpg --import <(echo "$GPG_PUBLIC_KEY")
                  #      gpg --allow-secret-key-import --import <(echo "$GPG_PRIVATE_KEY")


            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3

            - name: initialize PPA 
              env: 
                PACK_VERSION: ${{ steps.metadata.outputs.version }}
                #EMAIL: ${{ secrets.EMAIL }}
              run: |
                  #dh_make -p "testpackage-$PACK_VERSION" --single --native --copyright mit --email "$EMAIL"
                  dh_make -p "testpackage-$PACK_VERSION" --single --native --copyright mit --email thorntondwt@gmail.com
                  rm debian/*.ex
                  rm debian/*.EX

            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
