name: ppa

on:
  push:
    branches:
      - main
      - master

jobs:
    create-ppa:
        name: Create PPA
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true

            - name: Setup Go
              uses: actions/setup-go@v1
              with:
                  go-version: 1.15

            - name: Metadata
              id: metadata
              run: |
                  # todo handle these error cases
                  #git_description=$(git describe --tags --long) || echo "0.0.0-001-$(git rev-parse --short HEAD)"
                  git_description="0.0.0-001-$(git rev-parse --short HEAD)"
                  version=$(echo "${git_description}" | awk -F- '{print $(1)}' | sed 's/^v//')
                  revision=$(echo "${git_description}" | awk -F- '{print $(NF-1)}')
                  commit=$(echo "${git_description}" | awk -F- '{print $(NF)}'  | sed 's/^g//')
                  echo "::set-output name=version::$version"
                  echo "::set-output name=revision::$revision"
                  echo "::set-output name=commit::$commit"

            - name: Install packaging tools
              run: |
                  sudo apt-get install gnupg dput dh-make devscripts lintian -y

                  
            - name: Create PPA
              env:
                VERSION: ${{ steps.metadata.outputs.version }}
                #EMAIL: ${{ secrets.EMAIL }}
                GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                GPG_PRIVATE_PASSPHRASE: ${{ secrets.GPG_PRIVATE_PASSPHRASE }}
                GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
              run: ./.github/workflows/actions/create_ppa.sh

                  #- name: Setup tmate session
                  #  env:
                  #    VERSION: ${{ steps.metadata.outputs.version }}
                  #    #EMAIL: ${{ secrets.EMAIL }}
                  #    GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                  #    GPG_PRIVATE_PASSPHRASE: ${{ secrets.GPG_PRIVATE_PASSPHRASE }}
                  #    GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
                  # uses: mxschmitt/action-tmate@v3
